version: '3'

networks:
    main_net:

services:
    nginx: 
        image: nginx:stable
        volumes:
          - ./services/nginx/config/nginx.conf:/etc/nginx/nginx.conf
        ports:
          - 80:80
          - 444:443
        depends_on:
          - django
        networks:
            - main_net

    django:
        build: 
            context: ./services/envglobeldjango
            dockerfile: Dockerfile
        command: ["python","manage.py","runserver", "0.0.0.0:8000", "--noreload"]
        volumes:
            - "./services/envglobeldjango:/api"

        environment:
            PYTHONPATH: /api
            PYTHONUNBUFFERED: "True"
            DEBUG: "True"
        # env_file: .secret
        ports:
            - "8000:8000"
        networks:
            - main_net
    cubejs:
        build: ./services/cubejs
        command: npm run dev
        env_file:
            - ./services/cubejs/.env
        volumes:
            - ./services/cubejs:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "4000:4000"
        networks:
            - main_net

    frontend:
        image: frontend:dev
        build: 
            context: ./services/envglobeldjango/frontend
            dockerfile: Dockerfile.frontend
        command: npm run dev
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./services/envglobeldjango:/usr/src/app
            - /usr/src/app/node_modules
            # - ./services/django/logs:/root/.npm/_logs
        expose:
            - "9000"
        networks:
            - main_net
    
