version: '3'

networks:
    main_net:

services:
    nginx: 
        image: nginx:stable
        volumes:
          - ./services/nginx/config/nginx.conf:/etc/nginx/nginx.conf
          - "./static:/static"
        ports:
          - 80:80
          - 443:443
        depends_on:
          - django
          - cubejs
        networks:
            - main_net

    django:
        image: aquintero446/django:envglobel
        build: 
            context: ./services/envglobeldjango
            dockerfile: Dockerfile
        command: ["python","manage.py","runserver", "0.0.0.0:8000", "--noreload"]
        volumes:
            - "./services/envglobeldjango:/api"
            - "./static:/static"

        environment:
            PYTHONPATH: /api
            PYTHONUNBUFFERED: "True"
            DEBUG: "True"
        env_file: ./services/envglobeldjango/.env
        ports:
            - "8000:8000"
        networks:
            - main_net
    cubejs:
        image: aquintero446/cubejs:envglobel
        build: ./services/cubejs
        command: npm run dev
        env_file:
            - ./services/cubejs/.env
        volumes:
            - ./services/cubejs:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "4000:4000"
        networks:
            - main_net

    api_ml:
        image: aquintero446/flask:envglobel
        build:
            context: ./services/api_ml
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        volumes: 
            - ./services/api_ml:/app
        command: python app.py

    frontend:
        image: frontend:dev
        build: 
            context: ./services/envglobeldjango/frontend
            dockerfile: Dockerfile.frontend
        command: npm run dev
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./services/envglobeldjango/frontend:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "9000:9000"
        networks:
            - main_net

    
    
